// AUTO-GENERATED by `npm run new:app`. Edit app manifests, not this file.
import type { AppManifest } from "@/platform/manifest/schema";
import { manifest as directory } from "./directory/manifest";

export const apps: AppManifest[] = [directory];
