// AUTO-GENERATED by `npm run new:app`. Edit app manifests, not this file.
import type { AppManifest } from "@/platform/manifest/schema";
import { manifest as directory } from "./directory/manifest";
import { manifest as featureFlags } from "./feature-flags/manifest";
import { manifest as kycReview } from "./kyc-review/manifest";

export const apps: AppManifest[] = [directory, featureFlags, kycReview];
