/**
 * Scaffolding CLI: `npm run new:app -- <key> [--label "Nav label"]`
 *
 * Generates an app module already wired into auth, RBAC, audit, nav and the
 * data access layer, with a working empty screen.
 */
import { mkdirSync, readdirSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const appsDir = join(root, "src", "apps");
const routesDir = join(root, "src", "app", "apps");

function parseArgs(argv: string[]) {
  const labelIndex = argv.indexOf("--label");
  const label = labelIndex >= 0 ? argv[labelIndex + 1] : undefined;
  const positional = argv.filter(
    (a, i) => !a.startsWith("--") && !(labelIndex >= 0 && i === labelIndex + 1),
  );
  return { key: positional[0], label };
}

const { key, label } = parseArgs(process.argv.slice(2));

if (!key || !/^[a-z][a-z0-9-]*$/.test(key)) {
  console.error("Usage: npm run new:app -- <kebab-case-key> [--label \"Nav label\"]");
  process.exit(1);
}

const appDir = join(appsDir, key);
if (existsSync(appDir)) {
  console.error(`App "${key}" already exists at ${appDir}`);
  process.exit(1);
}

const title = label ?? key.replace(/-/g, " ").replace(/^./, (c) => c.toUpperCase());
const permission = `${key.replace(/-/g, "_")}.read`;

mkdirSync(appDir, { recursive: true });
writeFileSync(
  join(appDir, "manifest.ts"),
  `import { defineApp } from "@/platform/manifest/schema";

export const manifest = defineApp({
  key: "${key}",
  name: "${title}",
  description: "",
  // Declared, not decided: the platform enforces these.
  permissions: ["${permission}"],
  nav: {
    label: "${title}",
    path: "/apps/${key}",
    order: 100,
    permission: "${permission}",
  },
  // Declare data resources and their PII fields here; the data access layer
  // gates reads and strips PII fields server side.
  resources: [],
});
`,
);

writeFileSync(
  join(appDir, "View.tsx"),
  `import { requirePermission } from "@/platform/server";
import { manifest } from "./manifest";

export async function View() {
  // Session auth + RBAC enforcement happen here, in platform code.
  const actor = await requirePermission(manifest.nav.permission);

  return (
    <div>
      <h1 className="text-xl font-semibold">{manifest.name}</h1>
      <p className="mt-2 text-sm text-slate-500">
        Empty app module for {actor.email}. Read data with \`db\` inside
        \`asActor(actor, ...)\` and write it with \`mutate(...)\`.
      </p>
    </div>
  );
}
`,
);

writeFileSync(
  join(appDir, "actions.ts"),
  `"use server";

import { mutate } from "@/platform/data";
import { requirePermission } from "@/platform/server";
import { manifest } from "./manifest";

/** Example audited write. Delete or replace. */
export async function example(formData: FormData) {
  const actor = await requirePermission(manifest.nav.permission);
  void formData;
  void mutate;
  void actor;
}
`,
);

mkdirSync(join(routesDir, key), { recursive: true });
writeFileSync(
  join(routesDir, key, "page.tsx"),
  `import { View } from "@/apps/${key}/View";

export const dynamic = "force-dynamic";

export default function Page() {
  return <View />;
}
`,
);

// Regenerate the registry from the apps directory so nav, RBAC and the PII
// policy pick the new module up automatically.
const keys = readdirSync(appsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const identifier = (name: string) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

writeFileSync(
  join(appsDir, "registry.ts"),
  `// AUTO-GENERATED by \`npm run new:app\`. Edit app manifests, not this file.
import type { AppManifest } from "@/platform/manifest/schema";
${keys.map((k) => `import { manifest as ${identifier(k)} } from "./${k}/manifest";`).join("\n")}

export const apps: AppManifest[] = [${keys.map(identifier).join(", ")}];
`,
);

console.log(`Created app "${key}":
  src/apps/${key}/manifest.ts
  src/apps/${key}/View.tsx
  src/apps/${key}/actions.ts
  src/app/apps/${key}/page.tsx
Registry regenerated. Grant "${permission}" to a role in src/platform/rbac/roles.ts.`);
